template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/mushorg/glutton/protocols/interfaces:
    config:
      all: true
      dir: protocols/mocks/
      filename: mock_{{.InterfaceName | lower}}.go
      pkgname: mocks
      structname: Mock{{.InterfaceName}}
