dist: trusty

language: go
go:
  - 1.8.x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap-dev libnetfilter-queue-dev iptables-dev

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - docker build -t glutton .
  - docker run -d --privileged=true --name glutton glutton

script:
  - go test
  - docker ps | grep -q glutton
