dist: trusty

language: go
go:
  - 1.7.x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap-dev libnetfilter-queue-dev iptables-dev

install:
  - go get -v github.com/Masterminds/glide
  - glide install
  - glide update
  - docker build -t glutton .
  - docker run -d --privileged=true --name glutton glutton 

script:
  - go test
  - docker ps | grep -q glutton
