[[constraint]]
  branch = "master"
  name = "github.com/1lann/go-sip"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/Unknwon/com"
  version = "1.0.0"

[[constraint]]
  name = "github.com/docopt/docopt-go"
  version = "0.6.2"

[[constraint]]
  name = "github.com/kung-foo/freki"
  branch = "v2"

[[constraint]]
  branch = "master"
  name = "github.com/lunixbochs/vtclean"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
