site_name: Glutton Documentation
version: 1.0
nav:
  - Introduction: index.md
  - Setup: setup.md
  - Configuration: configuration.md
  - Extension: extension.md
  - FAQs: faq.md
theme:
  name: readthedocs

