# This file is part of FreePBX
#
# FreePBX configuration file for Elastix/FreePBX honeypot bait.

AMPDBENGINE=mysql
AMPDBHOST=localhost
AMPDBNAME=asterisk
AMPDBUSER=asteriskuser
AMPDBPASS=amp109
AMPENGINE=asterisk
AMPMGRUSER=admin
AMPMGRPASS=amp111
ASTETCDIR=/etc/asterisk
ASTVARLIBDIR=/var/lib/asterisk
ASTLOGDIR=/var/log/asterisk
