# Example:
#
# description: Glutton will redirect clients to following hosts list. Please update accordingly (Port->IP:Port).
# ports:
#    22:
#      proxy:localhost:5001       #Forward traffic to remote server
#    23:
#      handle:telnet              #Forward traffic to glutton built in telnet handler
#      
#Traffic to other ports will be handled by the default handler of glutton

default: handle:default

ports:
  22:
    proxy:localhost:5001
  23:
    handle:telnet
