# Example:
#
# description: Glutton will redirect clients to following hosts list. Please update accordingly (Port->IP:Port).
# ports:
#    22:
#      localhost:5001

default: handle:default

ports:
  22:
    proxy:localhost:5001
  23:
    handle:telnet
