rules:
  - match: tcp dst port 23 or port 2323 or port 23231
    type: conn_handler
    target: telnet
    tls: auto
  - match: tcp dst port 1883 or port 8883
    type: conn_handler
    target: mqtt
    tls: auto
  - match: tcp dst port 6969
    type: conn_handler
    target: bittorrent
  - match: tcp dst port 25
    type: conn_handler
    target: smtp
  - match: tcp dst port 3389
    type: conn_handler
    target: rdp
  - match: tcp dst portrange 5900-5910
    type: conn_handler
    target: rfb
  - match: tcp dst port 445
    type: conn_handler
    target: smb
  - match: tcp dst port 21
    type: conn_handler
    target: ftp
  - match: tcp dst port 5060
    type: conn_handler
    target: sip
  - match: udp dst port 5060
    type: conn_handler
    target: sip
  - match: tcp dst port 5222 or port 5223
    type: conn_handler
    target: jabber
  - match: tcp dst port 995
    type: conn_handler
    target: pop3
    tls: true
  - match: tcp dst port 43
    type: conn_handler
    target: whois
  - match: tcp dst port 11211
    type: conn_handler
    target: memcache
  - match: tcp dst port 3260
    type: conn_handler
    target: iscsi
  - match: tcp dst port 27017
    type: conn_handler
    target: mongodb
    tls: auto
  - match: tcp dst port 502
    type: conn_handler
    target: modbus
  - match: tcp dst port 20000
    type: conn_handler
    target: dnp3
  - match: tcp dst port 4840
    type: conn_handler
    target: opcua
  - match: tcp dst port 9000
    type: conn_handler
    target: mctp
  - match: tcp dst port 104 or port 11112
    type: conn_handler
    target: dicom
  - match: tcp dst port 25565
    type: conn_handler
    target: minecraft
  - match: tcp dst port 1080 or port 4145
    type: conn_handler
    target: socks
  - match: tcp
    type: conn_handler
    target: tcp
  - match: udp dst port 1194
    type: conn_handler
    target: openvpn
  - match: udp dst port 5353
    type: conn_handler
    target: mdns
  - match: udp dst port 1701
    type: conn_handler
    target: l2tp
  - match: udp dst port 19132
    type: conn_handler
    target: raknet
  - match: udp dst port 88
    type: conn_handler
    target: kerberos
  - match: udp dst port 5683
    type: conn_handler
    target: coap
  - match: udp dst port 500 or port 4500
    type: conn_handler
    target: ike
  - match: udp dst port 27015
    type: conn_handler
    target: a2s
  - match: udp dst port 987 or port 9302
    type: conn_handler
    target: ddp
  - match: udp dst port 7400 or port 7401 or port 7410 or port 7411
    type: conn_handler
    target: rtps
  - match: udp dst port 3671
    type: conn_handler
    target: knx
  - match: udp dst port 3702
    type: conn_handler
    target: wsdiscovery
  - match: udp
    type: conn_handler
    target: udp
