// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net"

	"github.com/mushorg/glutton/connection"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHoneypot creates a new instance of MockHoneypot. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHoneypot(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHoneypot {
	mock := &MockHoneypot{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHoneypot is an autogenerated mock type for the Honeypot type
type MockHoneypot struct {
	mock.Mock
}

type MockHoneypot_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHoneypot) EXPECT() *MockHoneypot_Expecter {
	return &MockHoneypot_Expecter{mock: &_m.Mock}
}

// ConnectionByFlow provides a mock function for the type MockHoneypot
func (_mock *MockHoneypot) ConnectionByFlow(uint64s [2]uint64) connection.Metadata {
	ret := _mock.Called(uint64s)

	if len(ret) == 0 {
		panic("no return value specified for ConnectionByFlow")
	}

	var r0 connection.Metadata
	if returnFunc, ok := ret.Get(0).(func([2]uint64) connection.Metadata); ok {
		r0 = returnFunc(uint64s)
	} else {
		r0 = ret.Get(0).(connection.Metadata)
	}
	return r0
}

// MockHoneypot_ConnectionByFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectionByFlow'
type MockHoneypot_ConnectionByFlow_Call struct {
	*mock.Call
}

// ConnectionByFlow is a helper method to define mock.On call
//   - uint64s [2]uint64
func (_e *MockHoneypot_Expecter) ConnectionByFlow(uint64s interface{}) *MockHoneypot_ConnectionByFlow_Call {
	return &MockHoneypot_ConnectionByFlow_Call{Call: _e.mock.On("ConnectionByFlow", uint64s)}
}

func (_c *MockHoneypot_ConnectionByFlow_Call) Run(run func(uint64s [2]uint64)) *MockHoneypot_ConnectionByFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 [2]uint64
		if args[0] != nil {
			arg0 = args[0].([2]uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHoneypot_ConnectionByFlow_Call) Return(metadata connection.Metadata) *MockHoneypot_ConnectionByFlow_Call {
	_c.Call.Return(metadata)
	return _c
}

func (_c *MockHoneypot_ConnectionByFlow_Call) RunAndReturn(run func(uint64s [2]uint64) connection.Metadata) *MockHoneypot_ConnectionByFlow_Call {
	_c.Call.Return(run)
	return _c
}

// GuardConn provides a mock function for the type MockHoneypot
func (_mock *MockHoneypot) GuardConn(conn net.Conn) net.Conn {
	ret := _mock.Called(conn)

	if len(ret) == 0 {
		panic("no return value specified for GuardConn")
	}

	var r0 net.Conn
	if returnFunc, ok := ret.Get(0).(func(net.Conn) net.Conn); ok {
		r0 = returnFunc(conn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	return r0
}

// MockHoneypot_GuardConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GuardConn'
type MockHoneypot_GuardConn_Call struct {
	*mock.Call
}

// GuardConn is a helper method to define mock.On call
//   - conn net.Conn
func (_e *MockHoneypot_Expecter) GuardConn(conn interface{}) *MockHoneypot_GuardConn_Call {
	return &MockHoneypot_GuardConn_Call{Call: _e.mock.On("GuardConn", conn)}
}

func (_c *MockHoneypot_GuardConn_Call) Run(run func(conn net.Conn)) *MockHoneypot_GuardConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.Conn
		if args[0] != nil {
			arg0 = args[0].(net.Conn)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHoneypot_GuardConn_Call) Return(conn1 net.Conn) *MockHoneypot_GuardConn_Call {
	_c.Call.Return(conn1)
	return _c
}

func (_c *MockHoneypot_GuardConn_Call) RunAndReturn(run func(conn net.Conn) net.Conn) *MockHoneypot_GuardConn_Call {
	_c.Call.Return(run)
	return _c
}

// MetadataByConnection provides a mock function for the type MockHoneypot
func (_mock *MockHoneypot) MetadataByConnection(conn net.Conn) (connection.Metadata, error) {
	ret := _mock.Called(conn)

	if len(ret) == 0 {
		panic("no return value specified for MetadataByConnection")
	}

	var r0 connection.Metadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(net.Conn) (connection.Metadata, error)); ok {
		return returnFunc(conn)
	}
	if returnFunc, ok := ret.Get(0).(func(net.Conn) connection.Metadata); ok {
		r0 = returnFunc(conn)
	} else {
		r0 = ret.Get(0).(connection.Metadata)
	}
	if returnFunc, ok := ret.Get(1).(func(net.Conn) error); ok {
		r1 = returnFunc(conn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHoneypot_MetadataByConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MetadataByConnection'
type MockHoneypot_MetadataByConnection_Call struct {
	*mock.Call
}

// MetadataByConnection is a helper method to define mock.On call
//   - conn net.Conn
func (_e *MockHoneypot_Expecter) MetadataByConnection(conn interface{}) *MockHoneypot_MetadataByConnection_Call {
	return &MockHoneypot_MetadataByConnection_Call{Call: _e.mock.On("MetadataByConnection", conn)}
}

func (_c *MockHoneypot_MetadataByConnection_Call) Run(run func(conn net.Conn)) *MockHoneypot_MetadataByConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.Conn
		if args[0] != nil {
			arg0 = args[0].(net.Conn)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHoneypot_MetadataByConnection_Call) Return(metadata connection.Metadata, err error) *MockHoneypot_MetadataByConnection_Call {
	_c.Call.Return(metadata, err)
	return _c
}

func (_c *MockHoneypot_MetadataByConnection_Call) RunAndReturn(run func(conn net.Conn) (connection.Metadata, error)) *MockHoneypot_MetadataByConnection_Call {
	_c.Call.Return(run)
	return _c
}

// ProduceTCP provides a mock function for the type MockHoneypot
func (_mock *MockHoneypot) ProduceTCP(protocol string, conn net.Conn, md connection.Metadata, payload []byte, decoded interface{}) error {
	ret := _mock.Called(protocol, conn, md, payload, decoded)

	if len(ret) == 0 {
		panic("no return value specified for ProduceTCP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, net.Conn, connection.Metadata, []byte, interface{}) error); ok {
		r0 = returnFunc(protocol, conn, md, payload, decoded)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHoneypot_ProduceTCP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceTCP'
type MockHoneypot_ProduceTCP_Call struct {
	*mock.Call
}

// ProduceTCP is a helper method to define mock.On call
//   - protocol string
//   - conn net.Conn
//   - md connection.Metadata
//   - payload []byte
//   - decoded interface{}
func (_e *MockHoneypot_Expecter) ProduceTCP(protocol interface{}, conn interface{}, md interface{}, payload interface{}, decoded interface{}) *MockHoneypot_ProduceTCP_Call {
	return &MockHoneypot_ProduceTCP_Call{Call: _e.mock.On("ProduceTCP", protocol, conn, md, payload, decoded)}
}

func (_c *MockHoneypot_ProduceTCP_Call) Run(run func(protocol string, conn net.Conn, md connection.Metadata, payload []byte, decoded interface{})) *MockHoneypot_ProduceTCP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 net.Conn
		if args[1] != nil {
			arg1 = args[1].(net.Conn)
		}
		var arg2 connection.Metadata
		if args[2] != nil {
			arg2 = args[2].(connection.Metadata)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 interface{}
		if args[4] != nil {
			arg4 = args[4].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockHoneypot_ProduceTCP_Call) Return(err error) *MockHoneypot_ProduceTCP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHoneypot_ProduceTCP_Call) RunAndReturn(run func(protocol string, conn net.Conn, md connection.Metadata, payload []byte, decoded interface{}) error) *MockHoneypot_ProduceTCP_Call {
	_c.Call.Return(run)
	return _c
}

// ProduceUDP provides a mock function for the type MockHoneypot
func (_mock *MockHoneypot) ProduceUDP(handler string, srcAddr *net.UDPAddr, dstAddr *net.UDPAddr, md connection.Metadata, payload []byte, decoded interface{}) error {
	ret := _mock.Called(handler, srcAddr, dstAddr, md, payload, decoded)

	if len(ret) == 0 {
		panic("no return value specified for ProduceUDP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *net.UDPAddr, *net.UDPAddr, connection.Metadata, []byte, interface{}) error); ok {
		r0 = returnFunc(handler, srcAddr, dstAddr, md, payload, decoded)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHoneypot_ProduceUDP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceUDP'
type MockHoneypot_ProduceUDP_Call struct {
	*mock.Call
}

// ProduceUDP is a helper method to define mock.On call
//   - handler string
//   - srcAddr *net.UDPAddr
//   - dstAddr *net.UDPAddr
//   - md connection.Metadata
//   - payload []byte
//   - decoded interface{}
func (_e *MockHoneypot_Expecter) ProduceUDP(handler interface{}, srcAddr interface{}, dstAddr interface{}, md interface{}, payload interface{}, decoded interface{}) *MockHoneypot_ProduceUDP_Call {
	return &MockHoneypot_ProduceUDP_Call{Call: _e.mock.On("ProduceUDP", handler, srcAddr, dstAddr, md, payload, decoded)}
}

func (_c *MockHoneypot_ProduceUDP_Call) Run(run func(handler string, srcAddr *net.UDPAddr, dstAddr *net.UDPAddr, md connection.Metadata, payload []byte, decoded interface{})) *MockHoneypot_ProduceUDP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *net.UDPAddr
		if args[1] != nil {
			arg1 = args[1].(*net.UDPAddr)
		}
		var arg2 *net.UDPAddr
		if args[2] != nil {
			arg2 = args[2].(*net.UDPAddr)
		}
		var arg3 connection.Metadata
		if args[3] != nil {
			arg3 = args[3].(connection.Metadata)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		var arg5 interface{}
		if args[5] != nil {
			arg5 = args[5].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockHoneypot_ProduceUDP_Call) Return(err error) *MockHoneypot_ProduceUDP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHoneypot_ProduceUDP_Call) RunAndReturn(run func(handler string, srcAddr *net.UDPAddr, dstAddr *net.UDPAddr, md connection.Metadata, payload []byte, decoded interface{}) error) *MockHoneypot_ProduceUDP_Call {
	_c.Call.Return(run)
	return _c
}

// ReplyUDP provides a mock function for the type MockHoneypot
func (_mock *MockHoneypot) ReplyUDP(srcAddr *net.UDPAddr, dstAddr *net.UDPAddr, payload []byte) error {
	ret := _mock.Called(srcAddr, dstAddr, payload)

	if len(ret) == 0 {
		panic("no return value specified for ReplyUDP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*net.UDPAddr, *net.UDPAddr, []byte) error); ok {
		r0 = returnFunc(srcAddr, dstAddr, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHoneypot_ReplyUDP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplyUDP'
type MockHoneypot_ReplyUDP_Call struct {
	*mock.Call
}

// ReplyUDP is a helper method to define mock.On call
//   - srcAddr *net.UDPAddr
//   - dstAddr *net.UDPAddr
//   - payload []byte
func (_e *MockHoneypot_Expecter) ReplyUDP(srcAddr interface{}, dstAddr interface{}, payload interface{}) *MockHoneypot_ReplyUDP_Call {
	return &MockHoneypot_ReplyUDP_Call{Call: _e.mock.On("ReplyUDP", srcAddr, dstAddr, payload)}
}

func (_c *MockHoneypot_ReplyUDP_Call) Run(run func(srcAddr *net.UDPAddr, dstAddr *net.UDPAddr, payload []byte)) *MockHoneypot_ReplyUDP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *net.UDPAddr
		if args[0] != nil {
			arg0 = args[0].(*net.UDPAddr)
		}
		var arg1 *net.UDPAddr
		if args[1] != nil {
			arg1 = args[1].(*net.UDPAddr)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHoneypot_ReplyUDP_Call) Return(err error) *MockHoneypot_ReplyUDP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHoneypot_ReplyUDP_Call) RunAndReturn(run func(srcAddr *net.UDPAddr, dstAddr *net.UDPAddr, payload []byte) error) *MockHoneypot_ReplyUDP_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConnectionTimeout provides a mock function for the type MockHoneypot
func (_mock *MockHoneypot) UpdateConnectionTimeout(ctx context.Context, conn net.Conn) error {
	ret := _mock.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConnectionTimeout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, net.Conn) error); ok {
		r0 = returnFunc(ctx, conn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHoneypot_UpdateConnectionTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConnectionTimeout'
type MockHoneypot_UpdateConnectionTimeout_Call struct {
	*mock.Call
}

// UpdateConnectionTimeout is a helper method to define mock.On call
//   - ctx context.Context
//   - conn net.Conn
func (_e *MockHoneypot_Expecter) UpdateConnectionTimeout(ctx interface{}, conn interface{}) *MockHoneypot_UpdateConnectionTimeout_Call {
	return &MockHoneypot_UpdateConnectionTimeout_Call{Call: _e.mock.On("UpdateConnectionTimeout", ctx, conn)}
}

func (_c *MockHoneypot_UpdateConnectionTimeout_Call) Run(run func(ctx context.Context, conn net.Conn)) *MockHoneypot_UpdateConnectionTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 net.Conn
		if args[1] != nil {
			arg1 = args[1].(net.Conn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHoneypot_UpdateConnectionTimeout_Call) Return(err error) *MockHoneypot_UpdateConnectionTimeout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHoneypot_UpdateConnectionTimeout_Call) RunAndReturn(run func(ctx context.Context, conn net.Conn) error) *MockHoneypot_UpdateConnectionTimeout_Call {
	_c.Call.Return(run)
	return _c
}
