on: push
name: Tests
jobs:
  checks:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install libpcap-dev iptables lsof
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.19"
      - run: make test
